secretsprovider: awskms:///arn:aws:kms:us-west-2:968153779208:alias/pulumi-secrets-key
encryptedkey: AQICAHhnm/1/W7/xeF2uxmXOGjFzOf6jjMX+KgbMb0K+LSCbsAGwxtZQaXmuKc6n1fmY5HZ8AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMaSgh27uH+NWc6zZTAgEQgDuYJdzIX0aniEtenDAzlCg46nfYlD+jVLRRzyyZZvWx0rBtMq5pl2pV8lLlq3ZG/GkWsPDNHhzak06DjQ==
config:
  aws:region: us-west-2
  prover:DOCKER_DIR: "../../"
  prover:SET_VERIFIER_ADDR: 0xEf0A93B2310d52358F1eCA0C946aD7D25596e7dd
  prover:PROOF_MARKET_ADDR: 0x006b92674E2A8d397884e293969f8eCD9f615f4C
  prover:BONSAI_API_URL: https://api.bonsai.xyz/
  prover:ORDER_STREAM_URL: https://order-stream.beboundless.xyz/
  prover:DOCKER_TAG: latest
  prover:BROKER_TOML_PATH: broker-staging.toml
  prover:BASE_STACK: organization/bootstrap/services-dev
  prover:ETH_RPC_URL:
    secure: v1:ZGilzSIhSnEnqene:E/RXZFjEwx3dC2+c7SLHOdkts59K/GYPXcy32z9tmion2hWHCnFGoRWgjfL0Yjk8iZGi3D9CvuHb7mj/oE0I6V0cD8CQIPfSpSi1cEQn3SSJKgJiJg==
  prover:PRIVATE_KEY:
    secure: v1:XeT00OsvvQdg9y4K:jjqy1PfadM1Zo6XwgwI4Z0NmwDYA4akd3HvpD1BKQFt6YqB2QS8l03uccezLX3uFRy67UecCwDYVlP4bG+Np1ClK2O/Wm0h5n2En5XlaslU=
  prover:BONSAI_API_KEY:
    secure: v1:R52O8izvZ2+jGU85:MXZSycsixFnVqErtbAvq5giYtIl5z8BOVwyDPgYHXAtuWzx3vqJ0gLYtR8fDiZDdqt2zvnroPfc=
