encryptionsalt: v1:8Ju5gqhO6S8=:v1:Qm4SNMiwFJVzvARi:dS7xuLb8mBc4rpjjD70dMbQTEvgygQ==
config:
  aws:region: us-west-2
  prover:environment: custom
  prover:gitBranch: ec2/debug
  prover:segmentSize: "21"
  prover:snarkTimeout: "180"
  prover:orderStreamUrl:
    secure: v1:X90ArDDqx5q+srIt:53bbJQKwb+ouD698BVDEm6kN0zYxCJ6ztqCQr404A6xBGLPGr2l88FnxIUnXGoY7bggq4w==
  prover:brokerPrivateKey:
    secure: v1:vfmrHKJlfKFFu+lc:qnyhRdoJXlbhFfS94rjVhTwk721I7CP+gGSFCETAUuL3nMZtOGlQ6l9s7xCXWd5BEEYgdxWwOVXoag2Fezf8Lmpliu3dq7NDXgAPLHZT/sM=
  prover:rpcUrl:
    secure: v1:tQkaIa2HXGIenAHF:MY4PsKaQ1BipRmmFIGOEYsUGUcLWUpyuW7i8/MQtD1TgSB6UmTWM9lfWvEfmYNe/AKCbaGzrkCmFOBb5ZCw6VECHbsWP8miACKvumI/SE6DjWN4r9zg=
  prover:rdsPassword:
    secure: v1:mBnN09ffWrI28wg+:ZIy9DyaYa7+v7eV3i31RXxxB5BKEpEGC
  prover:dockerToken:
    secure: v1:4ZuM7FUrVVnZszqq:j6woFQiGijyHT1iA3Sb2OnDM0oMfwPDar7LhgplISnpCF89MqsAfNqzTRooGRFO/Q6ukxEic8KJIQMCSpXqmRNry3BcBwbg+MKtC30wrcNkYd3UJA6obrXoC
  prover:boundlessMarketAddress: 0x26759dbB201aFbA361Bec78E097Aa3942B0b4AB8
  prover:setVerifierAddress: 0x8C5a8b5cC272Fe2b74D18843CF9C3aCBc952a760
