[workspace]
resolver = "2"
members = ["host", "guest"]
default-members = ["host"]

# Always optimize; building and running the guest takes much longer without optimization.
[profile.dev]
opt-level = 3

[profile.release]
debug = 1
lto = true

[patch.crates-io]
# TODO this might not be picked up by default, check versions once locked
sha2-v0-10-8 = { package = "sha2", git = "https://github.com/risc0/RustCrypto-hashes", tag = "sha2-v0.10.8-risczero.0" }
sha2-v0-9-9 = { package = "sha2", git = "https://github.com/risc0/RustCrypto-hashes", rev = "c2b5d71c687cbccf9235069732c050486a01b1b2" }
# sha2-v0-9-9 = { git = "https://github.com/risc0/RustCrypto-hashes", tag = "sha2-v0.9.9-risczero.0" }
crypto-bigint = { git = "https://github.com/risc0/RustCrypto-crypto-bigint", tag = "v0.5.2-risczero.0" }
