[workspace]
resolver = "2"
members = ["host", "core"]
default-members = ["host"]

[workspace.dependencies]
tendermint-rpc = "0.37.0"
tendermint = { version = "0.37.0", default-features = false }
tendermint-light-client-verifier = { version = "0.37.0", default-features = false, features = [
	"rust-crypto",
] }
serde = "1.0"
# TODO remove hopefully both of these
ciborium = "0.2"

# Always optimize; building and running the guest takes much longer without optimization.
[profile.dev]
opt-level = 3

[profile.release]
debug = 1
lto = true
