[workspace]
resolver = "2"
members = ["host", "core"]
default-members = ["host"]

[workspace.dependencies]
tendermint-rpc = "0.37.0"
tendermint = { version = "0.37.0", default-features = false }
tendermint-light-client-verifier = { version = "0.37.0", default-features = false, features = [
	"rust-crypto",
] }
serde = "1.0"
# TODO remove hopefully both of these
ciborium = "0.2"

# Always optimize; building and running the guest takes much longer without optimization.
[profile.dev]
opt-level = 3

[profile.release]
debug = 1
lto = true

[patch.crates-io]
sha2-v0-10-8 = { package = "sha2", git = "https://github.com/risc0/RustCrypto-hashes", tag = "sha2-v0.10.8-risczero.0" }
# TODO switch to tag when finalized
ed25519-consensus = { git = "https://github.com/risc0/ed25519-consensus", rev = "8a6d26d1fcd377f9322ba83d3732d04c157e4778" }
# ed25519-consensus = { path = "../../penumbra-zone/ed25519-consensus" }
crypto-bigint = { git = "https://github.com/risc0/RustCrypto-crypto-bigint", tag = "v0.5.5-risczero.0" }
