[package]
name = "resolve-guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
alloy-sol-types = "0.8"
boundless-market = { path = "../../../boundless-market", default-features = false }
boundless-resolve = { path = "../../../resolve" }
postcard = "1.0"
risc0-aggregation = { git = "https://github.com/risc0/risc0-ethereum", rev = "8a0d89e49d89aa18cbb0a28d81597b3f93bf38df" }
# NOTE: disable-dev-mode is critical to the security of use for the Receipt::verify in the guest.
risc0-zkvm = { version = "1.2", default-features = false, features = ["disable-dev-mode", "unstable"] }

[patch.crates-io]
# use optimized risc0 circuit
sha2 = { git = "https://github.com/risc0/RustCrypto-hashes", tag = "sha2-v0.10.8-risczero.0" }
k256 = { git = "https://github.com/risc0/RustCrypto-elliptic-curves", tag = "k256/v0.13.4-risczero.1" }
crypto-bigint = { git = "https://github.com/risc0/RustCrypto-crypto-bigint", tag = "v0.5.5-risczero.0" }
