[package]
name = "resolve-guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
aggregation-set = { path = "../../../aggregation-set", default-features = false, features = ["verify"] }
postcard = "1.0"
resolve = { path = "../../../resolve" }
# NOTE: disable-dev-mode is critical to the security of use for the Receipt::verify in the guest.
risc0-zkvm = { version = "1.0", default-features = false, features = ["std", "disable-dev-mode", "unstable"] }

[patch.crates-io]
# use optimized risc0 circuit
sha2 = { git = "https://github.com/risc0/RustCrypto-hashes", tag = "sha2-v0.10.8-risczero.0" }
k256 = { git = "https://github.com/risc0/RustCrypto-elliptic-curves", tag = "k256/v0.13.3-risczero.0" }
crypto-bigint = { git = "https://github.com/risc0/RustCrypto-crypto-bigint", tag = "v0.5.5-risczero.0" }
