[package]
name = "risc0-tm-core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
tiny-merkle = "0.3"
tiny-keccak = { version = "2.0", features = ["keccak"] }
thiserror = "1.0"