[package]
name = "network-test-layer"
version.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
alloy = { workspace = true, features = ["network", "providers", "transports", "json-rpc"] }
tower = "0.5.2"
tracing = { workspace = true }