[package]
name = "boundless-povw-guests"
resolver = "2"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
publish = false

[dev-dependencies]
alloy = { workspace = true, features = ["network", "node-bindings", "rpc-types", "providers", "transports", "sol-types", "contract", "signers", "signer-local"] }
anyhow = { workspace = true }
bytemuck = "1.23"
risc0-ethereum-contracts = { workspace = true, features = ["unstable"] }
risc0-povw-guests = { git = "https://github.com/risc0/risc0", branch = "victor/povw-circuit-updates" }
risc0-zkvm = { git = "https://github.com/risc0/risc0", branch = "victor/povw-circuit-updates", default-features = false, features = ["client", "unstable"] }
tokio = { workspace = true }

[build-dependencies]
risc0-build = { workspace = true, features = ["unstable"] }
risc0-build-ethereum = { workspace = true }

[package.metadata.risc0]
methods = ["mint-calculator", "log-updater"]

[package.metadata.release]
release = false
