name: Docker Build and Push

on:
  push:
    branches: [main]
    tags: ["v*"]

permissions:
  id-token: write
  attestations: write
  contents: read

jobs:
  build_agent:
    uses: NethermindEth/github-workflows/.github/workflows/docker-build-push-jfrog.yaml@main
    with:
      group_name: "angkor"
      runner: ubuntu-gigachad
      image_name: "boundless-agent"
      push: ${{ github.event_name != 'pull_request' }}
      dockerfile_path: "dockerfiles/agent.prebuilt.dockerfile"
      platforms: "linux/amd64"
      run_trivy: false
      docker_build_args: "BINARY_URL=https://github.com/boundless-xyz/boundless/releases/download/bento-v1.0.0/bento-bundle-linux-amd64.tar.gz"

  build_broker:
    uses: NethermindEth/github-workflows/.github/workflows/docker-build-push-jfrog.yaml@main
    with:
      group_name: "angkor"
      runner: ubuntu-gigachad
      image_name: "boundless-broker"
      push: ${{ github.event_name != 'pull_request' }}
      dockerfile_path: "dockerfiles/broker.prebuilt.dockerfile"
      platforms: "linux/amd64"
      run_trivy: false
      docker_build_args: "BINARY_URL=https://github.com/boundless-xyz/boundless/releases/download/broker-v1.0.0/broker"

  build_rest_api:
    uses: NethermindEth/github-workflows/.github/workflows/docker-build-push-jfrog.yaml@main
    with:
      group_name: "angkor"
      runner: ubuntu-gigachad
      image_name: "boundless-rest-api"
      push: ${{ github.event_name != 'pull_request' }}
      dockerfile_path: "dockerfiles/broker.prebuilt.dockerfile"
      platforms: "linux/amd64"
      run_trivy: false
      docker_build_args: "BINARY_URL=https://github.com/boundless-xyz/boundless/releases/download/bento-v1.0.0/bento-bundle-linux-amd64.tar.gz"
