name: Docker Build and Push

on:
  push:
    branches: [main]
    tags: ["v*"]

permissions:
  id-token: write
  attestations: write
  contents: read

jobs:
  build_simple:
    uses: NethermindEth/github-workflows/.github/workflows/docker-build-push-jfrog.yaml@main
    with:
      group_name: "angkor"
      runner: ubuntu-gigachad
      image_name: "boundless-agent"
      push: ${{ github.event_name != 'pull_request' }}
      dockerfile_path: "dockerfiles/agent.prebuilt.dockerfile"
      platforms: "linux/amd64"
      docker_build_args: "BINARY_URL=https://github.com/boundless-xyz/boundless/releases/download/bento-v1.0.0/bento-bundle-linux-amd64.tar.gz"
      pre_build_script: |
        # Clean up some space
        sudo rm -rf /usr/share/dotnet || true
        sudo rm -rf /usr/local/share/powershell || true
        sudo rm -rf /usr/lib/jvm || true
